# Generated by Django 3.0.5 on 2020-04-25 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('user', '0001_initial'),
        ('learner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionassignmentresult',
            name='session_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.SessionAssignment'),
        ),
        migrations.AddField(
            model_name='sessionassignmentresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionassignment',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.QuestionLevel'),
        ),
        migrations.AddField(
            model_name='sessionassignment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.MultipleAnswerQuestion'),
        ),
        migrations.AddField(
            model_name='sessionassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.Session'),
        ),
        migrations.AddField(
            model_name='sessionassignment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.QuestionType'),
        ),
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.Course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learner.Course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.Discount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learner.Session'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learner.Certificate'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learner.Course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.Discount'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.Schedule'),
        ),
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masterdata.Technology'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='learner.Course'),
        ),
    ]
