# Generated by Django 3.0.5 on 2020-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(default='EMAIL', help_text='EMAIL, GOOGLE, FB', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='firebase cloud token', max_length=128, null=True),
        ),
    ]
